# Generated by Django 5.2.3 on 2025-07-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("influencer", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InfluencerUser",
        ),
    ]
