# Generated by Django 5.0.14 on 2025-07-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instagramtoken",
            name="refresh_token",
        ),
    ]
