# Generated by Django 5.0.14 on 2025-07-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("company", "0002_remove_youtubetoken_channel_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=30)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("last_connected", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active_plan", models.CharField(default="free", max_length=30)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_reports", models.BooleanField(default=True)),
                ("campaign_end", models.BooleanField(default=True)),
                ("integration_error", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=False)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecuritySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("last_password_change", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyprofile",
                    ),
                ),
            ],
        ),
    ]
