# Generated by Django 5.0.14 on 2025-07-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("company", "0003_apiconnection_billinginfo_notificationpreference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconnection",
            name="is_active",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="billinginfo",
            name="auto_renew",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="campaign_end",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="email_reports",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="integration_error",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="push_enabled",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="oauthstate",
            name="provider",
            field=models.CharField(
                choices=[
                    ("ga4", "GA4"),
                    ("youtube", "YouTube"),
                    ("instagram", "Instagram"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securitysetting",
            name="two_factor_enabled",
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name="InstagramToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "instagram_business_account_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "facebook_page_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_data_fetch", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyprofile",
                    ),
                ),
            ],
        ),
    ]
